# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {R:/ECE 2029 Lab 2/Lab2/Lab2.cache/wt} [current_project]
set_property parent.project_path {R:/ECE 2029 Lab 2/Lab2/Lab2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {r:/ECE 2029 Lab 2/Lab2/Lab2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{R:/ECE 2029 Lab 2/Lab2/Lab2.srcs/sources_1/new/and_or_not_xor.v}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{R:/ECE 2029 Lab 2/Lab2/Lab2.srcs/constrs_1/new/and-or-not-xor.xdc}}
set_property used_in_implementation false [get_files {{R:/ECE 2029 Lab 2/Lab2/Lab2.srcs/constrs_1/new/and-or-not-xor.xdc}}]

read_xdc {{R:/ECE 2029 Lab 2/Lab2/Lab2.srcs/constrs_1/new/nand-nor-xnor-buf.xdc}}
set_property used_in_implementation false [get_files {{R:/ECE 2029 Lab 2/Lab2/Lab2.srcs/constrs_1/new/nand-nor-xnor-buf.xdc}}]


synth_design -top and_or_not_xor -part xc7a35tcpg236-1


write_checkpoint -force -noxdef and_or_not_xor.dcp

catch { report_utilization -file and_or_not_xor_utilization_synth.rpt -pb and_or_not_xor_utilization_synth.pb }
